#!/usr/local/bin/perl
##################################
# UNIQ - cmp sha against uniq list
##################################
use strict; use warnings;
my ($pmaster, $mmaster, $log) = @ARGV;
die "ARG1 target ARG2 master ARG3 log\n" unless (defined $log);
##################################
my %master;
##################################
open(my $pfp, '<', $pmaster) or die ("Couldn't open partialmaster\n");
open(my $mfp, '<', $mmaster) or die ("Couldn't open master\n");
open(my $lfp, '>>', $log) or die;
##################################
my @pfile = readline $pfp; chomp @pfile;
my @mfile = readline $mfp; chomp @mfile;
##################################
%master = map{$_ => undef} @mfile;
##################################
for (@pfile) 
{
	if (exists $master{$_}) 
		{ next; }
##################################
	else 
		{ print $lfp "$_\n"; }
}
##################################
