#!/bin/sh
. /etc/rc.subr
name="hive"
rcvar=hive_enable
#command="perl /bin/DEMON_TED"
load_rc_config $name
#run_rc_command "$1"
perl /usr/ANONI/HIVE/BIO/TED
perl /usr/ANONI/HIVE/BIO/ALEX
perl /usr/ANONI/HIVE/BIO/ZOE
perl /usr/ANONI/HIVE/BIO/CAM
perl /usr/ANONI/HIVE/BIO/WUF
